# @format

swagger: '2.0'
info:
  description: 'This is api documentation for event management app '
  version: '1.0.0'
  title: 'Event Management'
  name: 'Event Management'
  contact:
    email: 'daxcode89@gmail.com'
host: 'localhost:5000'
paths:
  /api/users/:
    get:
      tags:
        - 'Users'
      summary: 'Find All Users'
      description: 'Multiple status values can be provided with comma separated strings'
      operationId: 'findAllUsers'
      produces:
        - 'application/xml'
        - 'application/json'
      responses:
        '200':
          description: 'successful operation'
        '400':
          description: 'Invalid status value'
  /api/users/signup:
    post:
      tags:
        - 'Users SignUp page'
      summary: 'User register page'
      description: 'User registers here for his account with Email and password'
      operationId: 'userSignUp'
      produces:
        - 'application/json'
        - 'application/xml'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'List of input object'
          required: true
          schema:
            $ref: '#/definitions/signup'
      responses:
        '200':
          description: 'successful operation'
        '400':
          description: 'Invalid status value'
definitions:
  signup:
    type: 'object'
    properties:
    email:
      type: 'string'
    password:
      type: 'string'
xml:
  name: 'signup'
